/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;
import java.util.ArrayList;
import java.util.List;

public class BowlingGame {
  private List<Integer> rolls = new ArrayList<>();

  public void roll(int pins) {
    rolls.add(pins);
  }

  public int score() {
    int score = 0;
    int rollIndex = 0;

    for (int frame = 0; frame < 10; frame++) {
      if (isStrike(rollIndex)) { // STRIKE
        score += 10 + strikeBonus(rollIndex);
        rollIndex++;
      } else if (isSpare(rollIndex)) { // SPARE
        score += 10 + spareBonus(rollIndex);
        rollIndex += 2;
      } else { // Normal
        score += sumOfBallsInFrame(rollIndex);
        rollIndex += 2;
      }
    }

    return score;
  }

  private boolean isStrike(int rollIndex) {
    return rolls.get(rollIndex) == 10;
  }

  private boolean isSpare(int rollIndex) {
    return rolls.get(rollIndex) + rolls.get(rollIndex + 1) == 10;
  }

  private int strikeBonus(int rollIndex) {
    return rolls.get(rollIndex + 1) + rolls.get(rollIndex + 2);
  }

  private int spareBonus(int rollIndex) {
    return rolls.get(rollIndex + 2);
  }

  private int sumOfBallsInFrame(int rollIndex) {
    return rolls.get(rollIndex) + rolls.get(rollIndex + 1);
  }
}
