/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class BowlingGameTest {
    private BowlingGame game;

    @BeforeEach
    public void setUp() {
        game = new BowlingGame();
    }

    @Test
    public void testAllGutterBalls() {
        rollMany(20, 0);
        assertEquals(0, game.score(), "Score should be 0 when all rolls are gutter balls.");
    }

    @Test
    public void testAllOnes() {
        rollMany(20, 1);
        assertEquals(20, game.score(), "Score should be 20 when all rolls knock down 1 pin.");
    }

    @Test
    public void testOneSpare() {
        game.roll(5);
        game.roll(5); // SPARE
        game.roll(3);
        rollMany(17, 0);
        assertEquals(16, game.score(), "Score should be 16 when a spare is followed by 3 pins.");
    }

    @Test
    public void testOneStrike() {
        game.roll(10); // STRIKE
        game.roll(3);
        game.roll(4);
        rollMany(16, 0);
        assertEquals(24, game.score(), "Score should be 24 when a strike is followed by 3 and 4 pins.");
    }

    @Test
    public void testPerfectGame() {
        rollMany(12, 10);
        assertEquals(300, game.score(), "Score should be 300 for a perfect game.");
    }

    private void rollMany(int rolls, int pins) {
        for (int i = 0; i < rolls; i++) {
            game.roll(pins);
        }
    }
}
