/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class BowlingGameTest {
    @Test
    public void singleGame() {
        BowlingGame game1 = new BowlingGame(0, 0); // 两次扔球都没有碰到球
        assertEquals(0, game1.score());

        BowlingGame game2 = new BowlingGame(3, 4); // 两次扔球都没有将球瓶全部击倒
        assertEquals(7, game2.score());

        BowlingGame game3 = new BowlingGame(10, 3, 4); // STRIKE, 然后3和4倒瓶
        assertEquals(17, game3.score());
    }
}